name: Deploy to VPS Dev
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ENVIRONMENT: development
      DEV_USERNAME: ${{ secrets.DEV_USERNAME }}
      DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install @rollup/rollup-linux-x64-gnu
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hedgerow-gg:latest
          build-args: |
            ENVIRONMENT=${{ env.ENVIRONMENT }}
            DEV_USERNAME=${{ secrets.DEV_USERNAME }}
            DEV_PASSWORD=${{ secrets.DEV_PASSWORD }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          port: ${{secrets.VPS_SSH_PORT}}
          script: |
            cd ~/docker-apps/hedgerow-gg/dev
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner }}/hedgerow-gg:latest
            docker compose down
            docker compose up -d
            docker logout ghcr.io
